---
title: "re2r benckmark"
author: "Qin Wenfeng"
date: "`r Sys.Date()`"
output: 
    rmarkdown::html_vignette:
        self_contained: TRUE
vignette: >
  %\VignetteIndexEntry{benchmark on re2r}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Derived from Toby Dylan Hocking [tdhock/regex-tutorial
](https://github.com/tdhock/regex-tutorial)

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  error = FALSE,
  tidy = FALSE
)

options(digits = 3, microbenchmark.unit = "ms")
```

```{r}
library(re2r)
library(stringi)
library(microbenchmark)

max.N <- 25
times.list <- list()
for(N in 1:max.N){
  cat(sprintf("subject/pattern size %4d / %4d\n", N, max.N))
  subject <- paste(rep("a", N), collapse="")
  pattern <- paste(rep(c("a?", "a"), each=N), collapse="")
  regexp = re2(pattern)
  gc()
  N.times <- microbenchmark(
    ICU = stri_match(subject, regex = pattern),
    PCRE = regexpr(pattern, subject, perl = TRUE),
    TRE = regexpr(pattern, subject, perl = FALSE),
    RE2 = re2_match(subject, regexp),
    times = 10)
  times.list[[N]] <- data.frame(N, N.times)
}
times <- do.call(rbind, times.list)
save(times, file="times.RData")

library(ggplot2)
library(directlabels)

linear.legend <- ggplot()+
  ggtitle("Timing regular expressions in R, linear scale")+
  scale_y_continuous("seconds")+
  scale_x_continuous("subject/pattern size",
                     limits=c(1, 27),
                     breaks=c(1, 5, 10, 15, 20, 25))+
  geom_point(aes(N, time/1e9, color=expr),
             shape=1,
             data=times)
(linear.dl <- direct.label(linear.legend, "last.polygons"))
# png("figure-complexity-linear.png")
# print(linear.dl)
# dev.off()

log.legend <- ggplot()+
  ggtitle("Timing regular expressions in R, log scale")+
  scale_y_log10("seconds")+
  scale_x_log10("subject/pattern size",
                limits=c(1, 30),
                breaks=c(1, 5, 10, 15, 20, 25))+
  geom_point(aes(N, time/1e9, color=expr),
             shape=1,
             data=times)
(log.dl <- direct.label(log.legend, "last.polygons"))
# png("figure-complexity-log.png")
# print(log.dl)
# dev.off()
```
