// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/re2r.h"
#include <Rcpp.h>

using namespace Rcpp;

// cpp_get_groups
SEXP cpp_get_groups(SEXP regexp);
RcppExport SEXP _re2r_cpp_get_groups(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_groups(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_program_fanout
SEXP cpp_get_program_fanout(SEXP regexp);
RcppExport SEXP _re2r_cpp_get_program_fanout(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_program_fanout(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_regex_to_string
SEXP cpp_regex_to_string(SEXP regexp);
RcppExport SEXP _re2r_cpp_regex_to_string(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_regex_to_string(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_regex_mimicsPCRE
LogicalVector cpp_regex_mimicsPCRE(SEXP regexp);
RcppExport SEXP _re2r_cpp_regex_mimicsPCRE(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_regex_mimicsPCRE(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_named_groups
SEXP cpp_get_named_groups(SEXP regexp);
RcppExport SEXP _re2r_cpp_get_named_groups(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_named_groups(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_expression_size
int cpp_get_expression_size(SEXP regexp);
RcppExport SEXP _re2r_cpp_get_expression_size(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_expression_size(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_is_re2c_na
LogicalVector cpp_is_re2c_na(SEXP regexp);
RcppExport SEXP _re2r_cpp_is_re2c_na(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_re2c_na(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_pattern
SEXP cpp_get_pattern(SEXP regexp);
RcppExport SEXP _re2r_cpp_get_pattern(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_pattern(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_options
SEXP cpp_get_options(SEXP regexp);
RcppExport SEXP _re2r_cpp_get_options(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_options(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_quote_meta
SEXP cpp_quote_meta(CharacterVector input, bool parallel, size_t grain_size);
RcppExport SEXP _re2r_cpp_quote_meta(SEXP inputSEXP, SEXP parallelSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quote_meta(input, parallel, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_re2_compile
SEXP cpp_re2_compile(CharacterVector input, bool log_errors_value, bool utf_8_value, bool posix_syntax_value, bool case_sensitive_value, bool dot_nl_value, bool literal_value, bool longest_match_value, bool never_nl_value, bool never_capture_value, bool one_line_value, bool perl_classes_value, bool word_boundary_value, int64_t max_mem_value, bool simplify_value);
RcppExport SEXP _re2r_cpp_re2_compile(SEXP inputSEXP, SEXP log_errors_valueSEXP, SEXP utf_8_valueSEXP, SEXP posix_syntax_valueSEXP, SEXP case_sensitive_valueSEXP, SEXP dot_nl_valueSEXP, SEXP literal_valueSEXP, SEXP longest_match_valueSEXP, SEXP never_nl_valueSEXP, SEXP never_capture_valueSEXP, SEXP one_line_valueSEXP, SEXP perl_classes_valueSEXP, SEXP word_boundary_valueSEXP, SEXP max_mem_valueSEXP, SEXP simplify_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< bool >::type log_errors_value(log_errors_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type utf_8_value(utf_8_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type posix_syntax_value(posix_syntax_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type case_sensitive_value(case_sensitive_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type dot_nl_value(dot_nl_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type literal_value(literal_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type longest_match_value(longest_match_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type never_nl_value(never_nl_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type never_capture_value(never_capture_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type one_line_value(one_line_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type perl_classes_value(perl_classes_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type word_boundary_value(word_boundary_valueSEXP);
    Rcpp::traits::input_parameter< int64_t >::type max_mem_value(max_mem_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type simplify_value(simplify_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_re2_compile(input, log_errors_value, utf_8_value, posix_syntax_value, case_sensitive_value, dot_nl_value, literal_value, longest_match_value, never_nl_value, never_capture_value, one_line_value, perl_classes_value, word_boundary_value, max_mem_value, simplify_value));
    return rcpp_result_gen;
END_RCPP
}
// cpp_count
SEXP cpp_count(CharacterVector input, SEXP regexp, size_t anchor, bool parallel, size_t grain_size);
RcppExport SEXP _re2r_cpp_count(SEXP inputSEXP, SEXP regexpSEXP, SEXP anchorSEXP, SEXP parallelSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    Rcpp::traits::input_parameter< size_t >::type anchor(anchorSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_count(input, regexp, anchor, parallel, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_extract
SEXP cpp_extract(CharacterVector input, SEXP regexp, bool all, size_t anchor, bool parallel, size_t grain_size);
RcppExport SEXP _re2r_cpp_extract(SEXP inputSEXP, SEXP regexpSEXP, SEXP allSEXP, SEXP anchorSEXP, SEXP parallelSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    Rcpp::traits::input_parameter< bool >::type all(allSEXP);
    Rcpp::traits::input_parameter< size_t >::type anchor(anchorSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extract(input, regexp, all, anchor, parallel, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_locate
SEXP cpp_locate(CharacterVector input, SEXP regexp, bool all, bool parallel, size_t grain_size);
RcppExport SEXP _re2r_cpp_locate(SEXP inputSEXP, SEXP regexpSEXP, SEXP allSEXP, SEXP parallelSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    Rcpp::traits::input_parameter< bool >::type all(allSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_locate(input, regexp, all, parallel, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_match
SEXP cpp_match(CharacterVector input, SEXP regexp, bool value, size_t anchor, bool all, bool parallel, size_t grain_size);
RcppExport SEXP _re2r_cpp_match(SEXP inputSEXP, SEXP regexpSEXP, SEXP valueSEXP, SEXP anchorSEXP, SEXP allSEXP, SEXP parallelSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    Rcpp::traits::input_parameter< bool >::type value(valueSEXP);
    Rcpp::traits::input_parameter< size_t >::type anchor(anchorSEXP);
    Rcpp::traits::input_parameter< bool >::type all(allSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_match(input, regexp, value, anchor, all, parallel, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_replace
SEXP cpp_replace(CharacterVector input, SEXP regexp, CharacterVector rewrite_, bool global_, bool parallel, size_t grain_size);
RcppExport SEXP _re2r_cpp_replace(SEXP inputSEXP, SEXP regexpSEXP, SEXP rewrite_SEXP, SEXP global_SEXP, SEXP parallelSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type rewrite_(rewrite_SEXP);
    Rcpp::traits::input_parameter< bool >::type global_(global_SEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_replace(input, regexp, rewrite_, global_, parallel, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_regex_simplify
SEXP cpp_regex_simplify(SEXP regexp);
RcppExport SEXP _re2r_cpp_regex_simplify(SEXP regexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_regex_simplify(regexp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_split
SEXP cpp_split(CharacterVector input, SEXP regexp, NumericVector part, bool fixed, bool parallel, size_t grain_size);
RcppExport SEXP _re2r_cpp_split(SEXP inputSEXP, SEXP regexpSEXP, SEXP partSEXP, SEXP fixedSEXP, SEXP parallelSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type part(partSEXP);
    Rcpp::traits::input_parameter< bool >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_split(input, regexp, part, fixed, parallel, grain_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_subset
SEXP cpp_subset(CharacterVector input, SEXP regexp, size_t anchor, bool parallel, size_t grain_size, bool omit_na);
RcppExport SEXP _re2r_cpp_subset(SEXP inputSEXP, SEXP regexpSEXP, SEXP anchorSEXP, SEXP parallelSEXP, SEXP grain_sizeSEXP, SEXP omit_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< SEXP >::type regexp(regexpSEXP);
    Rcpp::traits::input_parameter< size_t >::type anchor(anchorSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< size_t >::type grain_size(grain_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type omit_na(omit_naSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_subset(input, regexp, anchor, parallel, grain_size, omit_na));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_re2r_cpp_get_groups", (DL_FUNC) &_re2r_cpp_get_groups, 1},
    {"_re2r_cpp_get_program_fanout", (DL_FUNC) &_re2r_cpp_get_program_fanout, 1},
    {"_re2r_cpp_regex_to_string", (DL_FUNC) &_re2r_cpp_regex_to_string, 1},
    {"_re2r_cpp_regex_mimicsPCRE", (DL_FUNC) &_re2r_cpp_regex_mimicsPCRE, 1},
    {"_re2r_cpp_get_named_groups", (DL_FUNC) &_re2r_cpp_get_named_groups, 1},
    {"_re2r_cpp_get_expression_size", (DL_FUNC) &_re2r_cpp_get_expression_size, 1},
    {"_re2r_cpp_is_re2c_na", (DL_FUNC) &_re2r_cpp_is_re2c_na, 1},
    {"_re2r_cpp_get_pattern", (DL_FUNC) &_re2r_cpp_get_pattern, 1},
    {"_re2r_cpp_get_options", (DL_FUNC) &_re2r_cpp_get_options, 1},
    {"_re2r_cpp_quote_meta", (DL_FUNC) &_re2r_cpp_quote_meta, 3},
    {"_re2r_cpp_re2_compile", (DL_FUNC) &_re2r_cpp_re2_compile, 15},
    {"_re2r_cpp_count", (DL_FUNC) &_re2r_cpp_count, 5},
    {"_re2r_cpp_extract", (DL_FUNC) &_re2r_cpp_extract, 6},
    {"_re2r_cpp_locate", (DL_FUNC) &_re2r_cpp_locate, 5},
    {"_re2r_cpp_match", (DL_FUNC) &_re2r_cpp_match, 7},
    {"_re2r_cpp_replace", (DL_FUNC) &_re2r_cpp_replace, 6},
    {"_re2r_cpp_regex_simplify", (DL_FUNC) &_re2r_cpp_regex_simplify, 1},
    {"_re2r_cpp_split", (DL_FUNC) &_re2r_cpp_split, 6},
    {"_re2r_cpp_subset", (DL_FUNC) &_re2r_cpp_subset, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_re2r(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
