# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_locate <- function(input, regexp, all, parallel, grain_size) {
    .Call('re2r_cpp_locate', PACKAGE = 're2r', input, regexp, all, parallel, grain_size)
}

cpp_match <- function(input, ptr, value, anchor, all, parallel, grain_size) {
    .Call('re2r_cpp_match', PACKAGE = 're2r', input, ptr, value, anchor, all, parallel, grain_size)
}

cpp_split <- function(input, ptr, part, fixed, parallel, grain_size) {
    .Call('re2r_cpp_split', PACKAGE = 're2r', input, ptr, part, fixed, parallel, grain_size)
}

cpp_re2_compile <- function(input, log_errors_value, utf_8_value, posix_syntax_value, case_sensitive_value, dot_nl_value, literal_value, longest_match_value, never_nl_value, never_capture_value, one_line_value, perl_classes_value, word_boundary_value, max_mem_value) {
    .Call('re2r_cpp_re2_compile', PACKAGE = 're2r', input, log_errors_value, utf_8_value, posix_syntax_value, case_sensitive_value, dot_nl_value, literal_value, longest_match_value, never_nl_value, never_capture_value, one_line_value, perl_classes_value, word_boundary_value, max_mem_value)
}

#' Get pre-compiled regular expression program size
#'
#' Returns the program size, a very approximate measure of a regexp's "cost".
#' Larger numbers are more expensive than smaller numbers.
#'
#' @param regexp a pre-compiled regular expression
#' @return a integer
#' @examples
#' regexp = re2("1")
#' get_expression_size(regexp)
#' @export
get_expression_size <- function(ptr) {
    .Call('re2r_get_expression_size', PACKAGE = 're2r', ptr)
}

cpp_get_pattern <- function(ptr) {
    .Call('re2r_cpp_get_pattern', PACKAGE = 're2r', ptr)
}

#' Return the number of capturing subpatterns
#'
#' Return the number of capturing subpatterns, or -1 if the
#' regexp wasn't valid on construction.  The overall match ($0)
#' does not count: if the regexp is "(a)(b)", returns 2.
#'
#' @param regexp a pre-compiled regular expression
#' @return a integer
#' @examples
#' regexp = re2("1")
#' get_number_of_groups(regexp)
#' @export
get_number_of_groups <- function(ptr) {
    .Call('re2r_get_number_of_groups', PACKAGE = 're2r', ptr)
}

cpp_get_named_groups <- function(ptr) {
    .Call('re2r_cpp_get_named_groups', PACKAGE = 're2r', ptr)
}

cpp_quote_meta <- function(input, parallel, grain_size) {
    .Call('re2r_cpp_quote_meta', PACKAGE = 're2r', input, parallel, grain_size)
}

cpp_replace <- function(input, regexp, rewrite, global_, parallel, grain_size) {
    .Call('re2r_cpp_replace', PACKAGE = 're2r', input, regexp, rewrite, global_, parallel, grain_size)
}

cpp_extract <- function(input, regexp, all, parallel, grain_size) {
    .Call('re2r_cpp_extract', PACKAGE = 're2r', input, regexp, all, parallel, grain_size)
}

cpp_get_program_fanout <- function(regexp) {
    .Call('re2r_cpp_get_program_fanout', PACKAGE = 're2r', regexp)
}

