# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('re2r_rcpp_hello', PACKAGE = 're2r')
}

re2_cpp_compile <- function(pattern, log_errors_value) {
    .Call('re2r_re2_cpp_compile', PACKAGE = 're2r', pattern, log_errors_value)
}

