# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_get_groups <- function(regexp) {
    .Call('re2r_cpp_get_groups', PACKAGE = 're2r', regexp)
}

cpp_get_program_fanout <- function(regexp) {
    .Call('re2r_cpp_get_program_fanout', PACKAGE = 're2r', regexp)
}

cpp_regex_to_string <- function(regexp) {
    .Call('re2r_cpp_regex_to_string', PACKAGE = 're2r', regexp)
}

cpp_regex_mimicsPCRE <- function(regexp) {
    .Call('re2r_cpp_regex_mimicsPCRE', PACKAGE = 're2r', regexp)
}

cpp_get_named_groups <- function(regexp) {
    .Call('re2r_cpp_get_named_groups', PACKAGE = 're2r', regexp)
}

cpp_get_expression_size <- function(regexp) {
    .Call('re2r_cpp_get_expression_size', PACKAGE = 're2r', regexp)
}

cpp_is_re2c_na <- function(regexp) {
    .Call('re2r_cpp_is_re2c_na', PACKAGE = 're2r', regexp)
}

cpp_get_pattern <- function(regexp) {
    .Call('re2r_cpp_get_pattern', PACKAGE = 're2r', regexp)
}

cpp_get_options <- function(regexp) {
    .Call('re2r_cpp_get_options', PACKAGE = 're2r', regexp)
}

cpp_quote_meta <- function(input, parallel, grain_size) {
    .Call('re2r_cpp_quote_meta', PACKAGE = 're2r', input, parallel, grain_size)
}

cpp_re2_compile <- function(input, log_errors_value, utf_8_value, posix_syntax_value, case_sensitive_value, dot_nl_value, literal_value, longest_match_value, never_nl_value, never_capture_value, one_line_value, perl_classes_value, word_boundary_value, max_mem_value, simplify_value) {
    .Call('re2r_cpp_re2_compile', PACKAGE = 're2r', input, log_errors_value, utf_8_value, posix_syntax_value, case_sensitive_value, dot_nl_value, literal_value, longest_match_value, never_nl_value, never_capture_value, one_line_value, perl_classes_value, word_boundary_value, max_mem_value, simplify_value)
}

cpp_count <- function(input, regexp, anchor, parallel, grain_size) {
    .Call('re2r_cpp_count', PACKAGE = 're2r', input, regexp, anchor, parallel, grain_size)
}

cpp_extract <- function(input, regexp, all, anchor, parallel, grain_size) {
    .Call('re2r_cpp_extract', PACKAGE = 're2r', input, regexp, all, anchor, parallel, grain_size)
}

cpp_locate <- function(input, regexp, all, parallel, grain_size) {
    .Call('re2r_cpp_locate', PACKAGE = 're2r', input, regexp, all, parallel, grain_size)
}

cpp_match <- function(input, regexp, value, anchor, all, parallel, grain_size) {
    .Call('re2r_cpp_match', PACKAGE = 're2r', input, regexp, value, anchor, all, parallel, grain_size)
}

cpp_replace <- function(input, regexp, rewrite_, global_, parallel, grain_size) {
    .Call('re2r_cpp_replace', PACKAGE = 're2r', input, regexp, rewrite_, global_, parallel, grain_size)
}

cpp_regex_simplify <- function(regexp) {
    .Call('re2r_cpp_regex_simplify', PACKAGE = 're2r', regexp)
}

cpp_split <- function(input, regexp, part, fixed, parallel, grain_size) {
    .Call('re2r_cpp_split', PACKAGE = 're2r', input, regexp, part, fixed, parallel, grain_size)
}

cpp_subset <- function(input, regexp, anchor, parallel, grain_size, omit_na) {
    .Call('re2r_cpp_subset', PACKAGE = 're2r', input, regexp, anchor, parallel, grain_size, omit_na)
}

